### ISSUE TITLE
introduction.ipynb contains a broken link to the BQL reference

### ISSUE THREAD

**Issue by mrosett** [probcomp/notebook#16]
Section 5.0 ("Documentation") contains the following broken link: https://probcomp-1.csail.mit.edu/reference/bayeslite/bql.html

**Comment by fsaad** [comment]
Thanks. The correct URL is http://probcomp.csail.mit.edu/dev/bayesdb/doc/bql.html.

**Comment by avinson** [comment]
fixed in https://github.com/probcomp/notebook/commit/7968920c6db2ace31c8b7f1cdad533a4dbd953bd
